### ISSUE TITLE
[BUG] Twitter blue checks not shown on Feed

### ISSUE THREAD

**Issue by AndiDink00x** [TheHCJ/Quacker#17]
Twitter blue checks still dont appear properly, as you can see blue checks are present neither in Feed nor on Twitter user account names but the blue check appears only in tweets in user's Twitter page

Using **2.1.0 version**
LineageOS 19.1
Android 12L

pics: 
https://imgur.com/a/9ovM3rq
https://imgur.com/a/X1XfNU6

**EDIT:**
Only when searching for Blue Twitter users the check appears correctly on their page
https://imgur.com/a/tHVzHEl

**Comment by TheHCJ** [comment]
I am aware of this issue. The feed has used a different way of displaying tweet cards as the rest of the app. I will try to get this fixed in v2.1.1

**Comment by j-fbriere** [comment]
Since I already have a fork of the Fritter project and that github do not allow to have another fork which is also a fork of the project Fritter, I can't fork Quacker. 
So I cannot do a PR for this project.
Instead, I will provide here the patch for this bug.
Here i is:
[fix_17.patch](https://github.com/TheHCJ/Quacker/files/11511233/fix_17.patch)

**Comment by TheHCJ** [comment]
Now merged your code changes in, should be in the next patch

**Comment by j-fbriere** [comment]
I saw the merge that you did. 
That last part of the fix:
```
    if (tweet.user != null) {
      tweet.user!.idStr = e['user_id_str'];
    }
```
was merged in the wrong function.
It should be in the **TweetWithCard.fromData** function, not the **TweetWithCard.fromJson** function.
It should be inserted at the line **#872** of the **lib/client.dart** file.
