### ISSUE TITLE
[BUG] Deleted Tweets Display A Unhelpful Error Message

### ISSUE THREAD

**Issue by TheHCJ** [TheHCJ/Quacker#8]
**Describe the problem that needs solving**
When clicking on a link of a deleted tweet it displays this error. [For testing here is a deleted tweet](https://twitter.com/portovechiaaa/status/1657403104759775246)

**Screenshots**
<img src="https://github.com/TheHCJ/Quacker/assets/109258788/6a41c547-ba92-4989-a5eb-88a47fbf4b99"
       alt="Screenshot of error"
       height="450">

_Originally posted by @ondern in https://github.com/TheHCJ/Quacker/issues/7#issuecomment-1546731958_

**Comment by j-fbriere** [comment]
This is to fix this issue of errors on deleted tweets on conversation threads.
Also instead of filtering out the deleted tweets, it displays tombstones.
patch from master commit 3705a7067ca7b768b8a75c2c396a89d664d922fa.
[fix_8.patch](https://github.com/TheHCJ/Quacker/files/11511844/fix_8.patch)

Note: I already sent a [PR](https://github.com/jonjomckay/fritter/pull/722) to the Fritter project 5 days ago, but it has not been merged.

**Comment by TheHCJ** [comment]
> Note: I already sent a [PR](https://github.com/jonjomckay/fritter/pull/722) to the Fritter project 5 days ago, but it has not been merged.

I have merged your change in, check the ci build for a usable apk
